services:
  client:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    depends_on:
      - server
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: Filestorix
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1024M

networks:
  my-network:

volumes:
  postgres-data:
